name: Dependency Updates

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

env:
  NODE_VERSION: '18'

jobs:
  # Check for outdated dependencies
  check-updates:
    name: Check for Updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check for outdated dependencies
        run: yarn outdated || true

      - name: Check for security vulnerabilities
        run: yarn audit --audit-level moderate || true

  # Automated security updates
  security-updates:
    name: Security Updates
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Update dependencies
        run: |
          yarn upgrade-interactive --latest
          yarn audit fix

      - name: Run tests
        run: yarn test:coverage

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: 'chore: automated dependency updates'
          body: |
            ## Automated Dependency Updates
            
            This PR contains automated updates for:
            - Security patches
            - Minor version updates
            
            ### Changes
            - Updated dependencies to latest compatible versions
            - Fixed security vulnerabilities
            
            ### Testing
            - [x] All tests passing
            - [x] No breaking changes detected
            
            Please review and merge if everything looks good.
          branch: chore/dependency-updates
          delete-branch: true 