name: Deploy

on:
  push:
    tags:
      - 'v*'

env:
  NODE_VERSION: '18'
  EXPO_CLI_VERSION: 'latest'

jobs:
  # Build and Deploy to Expo
  deploy-expo:
    name: Deploy to Expo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Setup Expo CLI
        uses: expo/expo-github-action@v8
        with:
          expo-version: ${{ env.EXPO_CLI_VERSION }}
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Run tests
        run: yarn test:coverage

      - name: Build for Android
        run: npx expo build:android --non-interactive

      - name: Build for iOS
        run: npx expo build:ios --non-interactive

      - name: Publish to Expo
        run: npx expo publish --non-interactive

  # Create GitHub Release
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: deploy-expo
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## What's Changed
            
            This release includes:
            - Bug fixes and improvements
            - Performance optimizations
            - New features
            
            ## Installation
            
            Download the latest version from the app store or scan the QR code in Expo Go.
          draft: false
          prerelease: false 